name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Ejecutar el pipeline solo en la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Iniciar sesión en Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 3. Construir la imagen Docker
      - name: Build Docker image
        run: |
          IMAGE_TAG=latest
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/node:$IMAGE_TAG .

      # 4. Empujar la imagen al ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/node:$IMAGE_TAG

      # 5. Actualizar el servicio en Amazon ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-new-ecs
          service: service-ecr-module-ecs
          cluster: curso-modulo-ecs
          wait-for-service-stability: true